"""regions and session tier config

Revision ID: 1870c2b342c5
Revises: c7b83b21e39b
Create Date: 2026-08-06 20:24:25.074942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1870c2b342c5'
down_revision: Union[str, None] = 'c7b83b21e39b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('polygon_geojson', sa.Text(), nullable=False),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('session_tier_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roll_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('max_rolls_per_session', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_tier_configs')
    op.drop_table('regions')
    # ### end Alembic commands ###
