"""workout distance for movement gate

Revision ID: 1e3e5fb62dd7
Revises: 2c207bbd1964
Create Date: 2026-08-07 17:11:30.357781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1e3e5fb62dd7'
down_revision: Union[str, None] = '2c207bbd1964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_workouts', sa.Column('distance_meters', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_workouts', 'distance_meters')
    # ### end Alembic commands ###
