"""wager config, declarations, payoffs

Revision ID: 2c207bbd1964
Revises: 7d4ff463e2bb
Create Date: 2026-08-07 16:38:25.369661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2c207bbd1964'
down_revision: Union[str, None] = '7d4ff463e2bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wager_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modest_session_threshold', sa.Integer(), nullable=False),
    sa.Column('standard_session_threshold', sa.Integer(), nullable=False),
    sa.Column('standard_bonus', sa.Integer(), nullable=False),
    sa.Column('ambitious_session_threshold', sa.Integer(), nullable=False),
    sa.Column('ambitious_bonus', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wager_declarations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('declared_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['wager_configs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_start', name='uq_wager_declarations_period')
    )
    op.create_table('wager_payoffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=True),
    sa.Column('qualifying_sessions', sa.Integer(), nullable=False),
    sa.Column('hit_target', sa.Boolean(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('roll_value', sa.Integer(), nullable=True),
    sa.Column('tier_result', sa.String(length=32), nullable=True),
    sa.Column('item_name', sa.String(length=255), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_start', name='uq_wager_payoffs_period')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wager_payoffs')
    op.drop_table('wager_declarations')
    op.drop_table('wager_configs')
    # ### end Alembic commands ###
