"""track ingest parse errors

Revision ID: 7d4ff463e2bb
Revises: 27f49ab2af62
Create Date: 2026-08-07 11:51:30.746434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7d4ff463e2bb'
down_revision: Union[str, None] = '27f49ab2af62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_ingest_events', sa.Column('parse_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_ingest_events', 'parse_error')
    # ### end Alembic commands ###
