"""drop tables

Revision ID: 9281da58361a
Revises: 1870c2b342c5
Create Date: 2026-08-06 21:03:20.311578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9281da58361a'
down_revision: Union[str, None] = '1870c2b342c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drop_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id')
    )
    op.create_table('drop_table_bands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drop_table_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('roll_min', sa.Integer(), nullable=False),
    sa.Column('roll_max', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['drop_table_id'], ['drop_tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drop_table_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('band_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['band_id'], ['drop_table_bands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drop_table_items')
    op.drop_table('drop_table_bands')
    op.drop_table('drop_tables')
    # ### end Alembic commands ###
