"""raw ingest storage

Revision ID: 975b3e94a4dc
Revises: 
Create Date: 2026-08-06 20:03:56.029915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '975b3e94a4dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_ingest_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_step_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingest_event_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('units', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['ingest_event_id'], ['raw_ingest_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingest_event_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('workout_type', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ingest_event_id'], ['raw_ingest_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_workout_route_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('sequence_index', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workout_id'], ['raw_workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_workout_route_points')
    op.drop_table('raw_workouts')
    op.drop_table('raw_step_samples')
    op.drop_table('raw_ingest_events')
    # ### end Alembic commands ###
