"""passive tier config and fragment ledger

Revision ID: c7b83b21e39b
Revises: 975b3e94a4dc
Create Date: 2026-08-06 20:09:34.607791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c7b83b21e39b'
down_revision: Union[str, None] = '975b3e94a4dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passive_tier_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('floor_steps', sa.Integer(), nullable=False),
    sa.Column('steps_per_fragment', sa.Integer(), nullable=False),
    sa.Column('daily_cap_fragments', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passive_fragment_awards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('award_date', sa.Date(), nullable=False),
    sa.Column('steps_counted', sa.Integer(), nullable=False),
    sa.Column('fragments_awarded', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['passive_tier_configs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('award_date', name='uq_passive_fragment_awards_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passive_fragment_awards')
    op.drop_table('passive_tier_configs')
    # ### end Alembic commands ###
