"""region unlocks and fragment ledger

Revision ID: e2a993655b7d
Revises: 9281da58361a
Create Date: 2026-08-06 21:09:25.094669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e2a993655b7d'
down_revision: Union[str, None] = '9281da58361a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fragment_ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('region_unlocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_id')
    )
    op.create_table('workout_roll_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('rolled_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['raw_workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(
        'regions',
        sa.Column('always_unlocked', sa.Boolean(), nullable=False, server_default=sa.text('0')),
    )
    op.add_column('regions', sa.Column('unlock_cost_fragments', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regions', 'unlock_cost_fragments')
    op.drop_column('regions', 'always_unlocked')
    op.drop_table('workout_roll_results')
    op.drop_table('region_unlocks')
    op.drop_table('fragment_ledger_entries')
    # ### end Alembic commands ###
